const express = require('express')
const router = express.Router()
const userController = require("../controllers/User")
const commentController = require('../controllers/Comment')
const locationController = require('../controllers/Location')


router.get('/', locationController.index)
router.get('/all-locations', locationController.show)
router.post('/create-location', locationController.create)
router.get('/new-location', locationController.new)
router.get('/:id/edit-location', locationController.edit)
router.patch('/:id', locationController.update)
router.delete('/:id', locationController.delete)
router.post('/:id/add-comment', commentController.create)
router.get('/:id/add-comment', commentController.new)
router.get('/:id/edit-comment', commentController.edit)
router.delete('/comment/:id', commentController.delete)
router.get('/users', userController.index)
router.get('/user-profile/:id', userController.show)
router.delete('/user-profile/:id/', userController.delete)
router.post('/create-user', userController.create)
router.get('/new-user', userController.new)

module.exports = router